import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SaleRecord } from '../types';
import { getLogoPngDataUrl } from '../components/Logo';

export async function generateInvoicePDF(sale: SaleRecord): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const logoImg = await getLogoPngDataUrl();

  // 1. Watermark Background
  if (logoImg) {
    try {
      doc.saveGraphicsState();
      const GState = (doc as unknown as { GState?: new (options: { opacity: number }) => unknown }).GState;
      if (GState) {
        doc.setGState(new GState({ opacity: 0.08 }));
      }
      doc.addImage(logoImg, 'PNG', 45, 85, 120, 120, undefined, 'FAST');
      doc.restoreGraphicsState();
    } catch (err) {
      console.warn('Watermark rendering notice:', err);
    }
  }

  // 2. Header with Logo & Brand Text
  if (logoImg) {
    try {
      doc.addImage(logoImg, 'PNG', 14, 12, 22, 22, undefined, 'FAST');
    } catch (err) {
      console.warn('Header logo notice:', err);
    }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(20, 38, 66); // Navy blue brand color
  doc.text('INDIA AUTOMOBILES', 40, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(50, 50, 50);
  doc.text('Proprietor: Khaja Mungle  |  Contact: +91 8055650977', 40, 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 100, 100);
  doc.text('Local Inventory & Customer Billing Management System', 40, 29);

  doc.setDrawColor(220, 220, 220);
  doc.line(14, 36, 196, 36);

  // 3. Invoice & Customer Meta
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(`INVOICE: ${sale.id}`, 14, 43);

  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date(sale.timestamp).toLocaleString()}`, 14, 49);
  doc.text(`Customer Name: ${sale.customer.name}`, 14, 55);
  doc.text(`Contact: ${sale.customer.contact}`, 14, 61);

  // 4. Line Items Table
  const tableData = sale.items.map(item => [
    item.code || '-',
    item.name,
    item.qty.toString(),
    `Rs. ${(Number(item.basePrice) || 0).toFixed(2)}`,
    item.discountPct ? `${item.discountPct}%` : '0%',
    `Rs. ${(Number(item.price) || 0).toFixed(2)}`,
    `Rs. ${(Number(item.total) || 0).toFixed(2)}`
  ]);

  autoTable(doc, {
    startY: 67,
    head: [['Item Code', 'Item Name', 'Qty', 'Base Price', 'Disc', 'Unit Price', 'Total']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [20, 38, 66] },
    margin: { left: 14, right: 14 }
  });

  const lastTableY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || 70;
  let finalY = lastTableY + 10;
  if (finalY > 225) {
    doc.addPage();
    finalY = 20;
  }

  // 5. Total Calculations
  doc.setFont('helvetica', 'normal');
  doc.text(`Subtotal: Rs. ${(sale.subtotal || sale.total).toFixed(2)}`, 130, finalY);
  if (sale.discountAmount) {
    doc.text(`Bill Discount: - Rs. ${sale.discountAmount.toFixed(2)}`, 130, finalY + 6);
  }
  doc.setFont('helvetica', 'bold');
  doc.text(`Grand Total: Rs. ${sale.total.toFixed(2)}`, 130, finalY + (sale.discountAmount ? 12 : 6));
  doc.setFont('helvetica', 'normal');
  doc.text(`Payment Option: ${sale.paymentMode || 'Cash'}`, 130, finalY + (sale.discountAmount ? 18 : 12));
  doc.text(`Paid: Rs. ${sale.paid.toFixed(2)}`, 130, finalY + (sale.discountAmount ? 24 : 18));
  doc.text(`Remaining Balance: Rs. ${sale.balance.toFixed(2)}`, 130, finalY + (sale.discountAmount ? 30 : 24));

  doc.setFontSize(8.5);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'bold');
  doc.text(`Generated by: ${sale.generatedBy || 'Admin'}`, 14, finalY + 34);

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for choosing India Automobiles! Visit again.', 14, finalY + 40);

  doc.save(`Invoice_${sale.id}.pdf`);
}

export async function generateLedgerPDF(
  customerName: string,
  contact: string,
  orders: SaleRecord[],
  generatedBy: string
): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const logoImg = await getLogoPngDataUrl();

  if (logoImg) {
    try {
      doc.saveGraphicsState();
      const GState = (doc as unknown as { GState?: new (options: { opacity: number }) => unknown }).GState;
      if (GState) {
        doc.setGState(new GState({ opacity: 0.08 }));
      }
      doc.addImage(logoImg, 'PNG', 45, 95, 120, 120, undefined, 'FAST');
      doc.restoreGraphicsState();
    } catch (err) {
      console.warn('Ledger watermark notice:', err);
    }
  }

  if (logoImg) {
    try {
      doc.addImage(logoImg, 'PNG', 14, 12, 22, 22, undefined, 'FAST');
    } catch (err) {
      console.warn('Ledger header logo notice:', err);
    }
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(20, 38, 66);
  doc.text('INDIA AUTOMOBILES', 40, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(50, 50, 50);
  doc.text('Proprietor: Khaja Mungle  |  Contact: +91 8055650977', 40, 24);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 100, 100);
  doc.text('Customer Account Ledger Statement', 40, 29);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 38);

  doc.setDrawColor(220, 220, 220);
  doc.line(14, 40, 196, 40);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(`Customer Name: ${customerName}`, 14, 47);
  doc.setFont('helvetica', 'normal');
  doc.text(`Contact: ${contact}`, 14, 53);

  let totalSpent = 0;
  let totalPaid = 0;
  let totalDue = 0;

  const tableData = orders.map(o => {
    totalSpent += Number(o.total) || 0;
    totalPaid += Number(o.paid) || 0;
    totalDue += Number(o.balance) || 0;
    const itemsText = (o.items || []).map(i => `${i.name} [${i.code || '-'}] x${i.qty}`).join(', ');
    return [
      o.id,
      new Date(o.timestamp).toLocaleDateString(),
      itemsText,
      `Rs. ${(Number(o.total) || 0).toFixed(2)}`,
      `Rs. ${(Number(o.paid) || 0).toFixed(2)}`,
      `Rs. ${(Number(o.balance) || 0).toFixed(2)}`
    ];
  });

  autoTable(doc, {
    startY: 59,
    head: [['Invoice ID', 'Date', 'Items Purchased', 'Total', 'Paid', 'Due Bal']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [20, 38, 66] },
    margin: { left: 14, right: 14 }
  });

  const lastTableY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY || 60;
  const finalY = lastTableY + 10;
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Purchases: Rs. ${totalSpent.toFixed(2)}`, 130, finalY);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Paid: Rs. ${totalPaid.toFixed(2)}`, 130, finalY + 6);
  doc.setTextColor(totalDue > 0 ? 220 : 0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Outstanding Due: Rs. ${totalDue.toFixed(2)}`, 130, finalY + 12);

  doc.setFontSize(8.5);
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by: ${generatedBy || 'Admin'}`, 14, finalY + 18);

  doc.save(`Ledger_${customerName.replace(/\s+/g, '_')}_${contact}.pdf`);
}
