import { SaleRecord } from '../types';

export function formatWhatsAppUrlForSale(sale: SaleRecord): string {
  if (!sale || !sale.customer || !sale.customer.contact) return '#';
  let phone = sale.customer.contact.replace(/\D/g, '');
  if (phone.length === 10) {
    phone = '91' + phone;
  }

  let itemsList = '';
  sale.items.forEach((item, index) => {
    const codeText = item.code && item.code !== '-' ? ` [${item.code}]` : '';
    const discText = item.discountPct ? ` (Disc: ${item.discountPct}%)` : '';
    itemsList += `${index + 1}. *${item.name}*${codeText} x${item.qty}${discText} = ₹${(Number(item.total) || 0).toFixed(2)}\n`;
  });

  const dateStr = new Date(sale.timestamp).toLocaleString();
  const message =
`*INDIA AUTOMOBILES - Invoice / Bill*
--------------------------------
👤 *Proprietor:* Khaja Mungle
📞 *Owner Contact:* +91 8055650977
📄 *Invoice ID:* ${sale.id}
📅 *Date:* ${dateStr}
👤 *Customer:* ${sale.customer.name}
📱 *Customer Phone:* ${sale.customer.contact}

*Purchased Items & Codes:*
${itemsList}--------------------------------
💰 *Subtotal:* ₹${(Number(sale.subtotal) || Number(sale.total)).toFixed(2)}
${sale.discountAmount ? `🎁 *Discount:* -₹${Number(sale.discountAmount).toFixed(2)}\n` : ''}💵 *Grand Total:* ₹${Number(sale.total).toFixed(2)}
💳 *Payment Mode:* ${sale.paymentMode || 'Cash'}
✅ *Amount Paid:* ₹${Number(sale.paid).toFixed(2)}
${Number(sale.balance) > 0 ? `⚠️ *Remaining Balance (Due):* ₹${Number(sale.balance).toFixed(2)}\n` : `✨ *Status:* Fully Paid (₹0.00 Due)\n`}--------------------------------
✍️ *Generated by:* ${sale.generatedBy || 'Admin'}
_Thank you for choosing India Automobiles!_`;

  return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
}

export function formatWhatsAppUrlForLedger(
  customerName: string,
  contact: string,
  orders: SaleRecord[]
): string {
  let phone = contact.replace(/\D/g, '');
  if (phone.length === 10) {
    phone = '91' + phone;
  }

  let totalSpent = 0;
  let totalPaid = 0;
  let totalDue = 0;
  orders.forEach(o => {
    totalSpent += Number(o.total) || 0;
    totalPaid += Number(o.paid) || 0;
    totalDue += Number(o.balance) || 0;
  });

  const recentOrdersStr = orders.slice(0, 5).map((o, idx) =>
    `${idx + 1}. *${o.id}* (${new Date(o.timestamp).toLocaleDateString()}) - Total: ₹${o.total.toFixed(2)}, Due: ₹${o.balance.toFixed(2)}`
  ).join('\n');

  const message =
`*INDIA AUTOMOBILES - Customer Account Ledger*
--------------------------------
👤 *Proprietor:* Khaja Mungle (+91 8055650977)
👤 *Customer:* ${customerName}
📱 *Phone:* ${contact}
📅 *Date:* ${new Date().toLocaleDateString()}

📊 *Account Summary:*
🛒 *Total Orders:* ${orders.length}
💰 *Total Purchases:* ₹${totalSpent.toFixed(2)}
✅ *Total Paid:* ₹${totalPaid.toFixed(2)}
${totalDue > 0 ? `⚠️ *Outstanding Balance (Due):* ₹${totalDue.toFixed(2)}\n` : `✨ *Status:* Fully Cleared (₹0 Due)\n`}
*Recent Invoices:*
${recentOrdersStr}
--------------------------------
_Thank you for your business with India Automobiles! For queries, contact Khaja Mungle (8055650977)._`;

  return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
}
